name: Build and Deploy with npm

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies with npm
        run: npm install

      - name: Build project
        run: npm run build

      - name: Copy build to workspace
        run: |
          rm -rf dist
          cp -r ../dist ./dist

      - name: Deploy via SSH
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "dist/"
          target: "/opt"
